### ISSUE TITLE
Strange error in the WebUI

### ISSUE THREAD

**Issue by halgari** [vrx-666/bacula-server#1]
I installed this via the sqlite backend, but when I load up the web UI, all my text has `@@` at both the start and end of every text string in the UI, so I'll see stuff like this in the HTML

`<h1>@@Bacula Server@@</h1>`

`<p>@@Jobs@@</p>`

Any idea what could be causing this?

**Comment by vrx-666** [comment]
What is Your host OS?

**Comment by halgari** [comment]
I’m running the docker off of a stock Unraid install.

**Comment by halgari** [comment]
If it helps here's some images:

![bacula1](https://user-images.githubusercontent.com/654621/150727649-b4d9c425-e521-4c83-803a-3fadc8b68cd3.png)

And as you can see, the issue is in the html source itself:

![bacula2](https://user-images.githubusercontent.com/654621/150727680-05bf3424-1980-407f-bf6d-c97515e4a439.png)

**Comment by vrx-666** [comment]
Thanks for images. I try to check this today's afternoon, but I'm little sick and can't guarantee that.

**Comment by vrx-666** [comment]
This is strange, but new version is building now, will be ready in few minutes.

**Comment by vrx-666** [comment]
Update is ready, If You have any error starting container after update give me any feedback, or You could Delete it (You do not need to deleta image), and install again with same path's, ports, and other settings. Nothing should disapear, any backups and history.

**Comment by vrx-666** [comment]
resolved
