### ISSUE TITLE
Postgre SQL error

### ISSUE THREAD

**Issue by karlkashofer** [vrx-666/bacula-server#2]
Hi !
Thanks for this great repo ! I try to test your bacula docker image but unfortunately get an error.

I built the image and use the following docker-compose file:
`version: "2"

services:
  BaculaServer:
     restart: unless-stopped
     image: bacula-server:11-postgresql
     environment:
       DB_Host: 'bacula-pg'
       DB_User: 'bacula'
       DB_Password: 'bacula'
       TZ: 'Europe/Vienna'
       SD_Host: 192.168.1.122
       WEB_User: 'admin'
       WEB_Password: 'difficult'
     ports:
       - '9103:9103'
       - '9095:9095'
     volumes:
       - $PWD/bacula-srv/working:/opt/bacula/working
       - $PWD/bacula-srv/etc:/opt/bacula/etc
       - $PWD/bacula-srv/storage:/mnt/bacula
       - $PWD/bacula-srv/log/bacula:/opt/bacula/log
       - $PWD/bacula-srv/log/apache2:/var/log/apache2
       - $PWD/bacula-srv/baculum:/etc/baculum
     depends_on:
       - bacula-pg

  bacula-pg:
     image: postgres
     restart: always
     environment:
       POSTGRES_USER: 'bacula'
       POSTGRES_PASSWORD: 'bacula'
       POSTGRES_INITDB_ARGS: "--encoding=SQL_ASCII"
     volumes:
       - $PWD/bacula-srv/postgresql:/var/lib/postgresql/data
`
here the docker compose file with better formatting: https://pastebin.com/Y7Pb7Gci

This errors out with "ERROR:  UNION types "char" and text cannot be matched at character" as soon as i access the baculum gui. Adding or removing the SQL_ASCII line does not make a difference.

Any idea what i am doing wrong ?
Thanks,
Karl

**Comment by vrx-666** [comment]
please try with postgres<=14
Readme will be updated soon.
