### ISSUE TITLE
Add bacula version 13 ?

### ISSUE THREAD

**Issue by karlkashofer** [vrx-666/bacula-server#4]
Hi !
Could you revive your version selection and include bacula version 13 ?

I just tested it, by just changing the version string in build.sh from 11 to 13 and it builds and runs flawĺessly !
Very nice build-workflow by the way ! :)

Sorry for missing the client repo and for communicating via issues, i dont see an email anywhere.

**Comment by vrx-666** [comment]
Changing version number in build.sh only change tag name, but docker is still build from Dockerfile-11, and is using Bacula 11 src.
Bacula 13 passed first tests but, there is no dedicated Baculum version. I would like to publish version 13 along with the new webUI version.

**Comment by vrx-666** [comment]
Here You have Bacula 13, but with older Baculum Web Interface, should working good.
https://github.com/vrx-666/bacula-server/tree/Bacula13

**Comment by vrx-666** [comment]
There is new update in Bacula-13 - new WEB Interface, be careful when updating container (path exchange and port change is needed, more info on docker hub:  https://hub.docker.com/r/pwa666/bacula-server (#Upgrading v11 to v13)
