### ISSUE TITLE
Baculum console not working

### ISSUE THREAD

**Issue by karlkashofer** [vrx-666/bacula-server#5]
Hi !

I cant figure out why, but the console in baculum (the icon under Welcome on top) does not work, it only gives invalid command.

Or am i missing something here ?

**Comment by vrx-666** [comment]
What commands did You tried?
I've checked that "help" is not working in baculum, but from shell is working as expected, but other commands are working.

**Comment by karlkashofer** [comment]
You are right. I naturally tried help.... only....

Closing.

Wonder why help does not work though.
