### ISSUE TITLE
Error on Restore Wizard

### ISSUE THREAD

**Issue by cerltuka** [vrx-666/bacula-server#9]
Hi, I'm getting this error when I try to use the restore wizard

![image](https://github.com/vrx-666/bacula-server/assets/169263630/8b300902-ec7a-42dd-86f5-544c43fec5da)

**Comment by vrx-666** [comment]
Error message is correct, there should not be any table named "b269472".
Which image version You are using? Is it upgraded from any previous versions?

**Comment by cerltuka** [comment]
id: sha256:8fd3b83f61779f000e212e81ae95e1e0f88dbb8395ab9ef4e4babe7830cdaac9		tag: pwa666/bacula-server:latest	created 2023-12-31 10:26:01

clean installation, no upgrade.

**Comment by vrx-666** [comment]
Could You please save this image (https://docs.docker.com/reference/cli/docker/image/save/) and share it for me (wetransfer, google drive or else)?
I don't see this sha256 digest on docker hub, it may be that the image had a bug and was deleted, don't remember.

**Comment by cerltuka** [comment]
https://drive.google.com/file/d/15PPrQTJwymiD2gancNSfbG00W9-H8zHI/view?usp=sharing

**Comment by vrx-666** [comment]
Thanks.
I've checked, and probably webui have a bug, aditionally this is pretty old version (Bacula 11).
If You have correctly binded path "Bacula working directory" (container path /opt/bacula/working) to something on the host, You could update image to 13 version, for example:  pwa666/bacula-server:13-sqlite3-b13 (this version has new webui "bacularis", and You must change container port 9095 -> 9097). After this upgrade everything should work, including "Restore" from webui.
Please let me know if this solved the problem.
*Upgrading from the version you are using to the latest version 15 has not been tested.

**Comment by vrx-666** [comment]
If You do not have binded container path /opt/bacula/working to some path on the host let me know, I will write how to solve this problem so as not to lose data and not to complicate the current situation.

**Comment by cerltuka** [comment]
worked perfectly after upgrading to version 13 with bacularis. thanks for your help.
